- name: Run the Action
  uses: devops-infra/action-pull-request@v0.5.5
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    source_branch: development
    target_branch: master
    title: Subindo alterações para o master
    template: .github/PULL_REQUEST_TEMPLATE.md
    body: "**Automated pull request**"
    reviewer: octocat
    assignee: octocat
    label: enhancement
    milestone: My milestone
    draft: true
    old_string: "<!-- Add your description here -->"
    new_string: "** Automatic pull request**"
    get_diff: true
    ignore_users: "dependabot"
    allow_no_diff: false
